KutuphaneYonetimSistemi/KutuphaneYonetimSistemi/Controllers/PanelimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using KutuphaneYonetimSistemi.Models.Entity;

namespace KutuphaneYonetimSistemi.Controllers
{
    public class PanelimController : Controller
    {
        // GET: Panelim
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        [HttpGet]
        [Authorize] // Authorize sayesinde kullanıcı adı ve şifresini girip, giriş yapmadan panelim sayfasına yönlendirilmez.
        public ActionResult Index()
        {
            var uyemail = (string)Session["Mail"];
            var degerler = db.TBLUYELER.FirstOrDefault(z => z.MAİL == uyemail);
            return View(degerler);
        }
        [HttpPost]
        public ActionResult Index2(TBLUYELER p)
        {
            var kullanici = (string)Session["Mail"];
            var uye = db.TBLUYELER.FirstOrDefault(x => x.MAİL == kullanici);
            uye.SİFRE = p.SİFRE;
            uye.AD = p.AD;
            uye.FOTOGRAF = p.FOTOGRAF;
            uye.OKUL = p.OKUL;
            uye.KULLANICIADI = p.KULLANICIADI;
            db.SaveChanges();
            return View(db);
        }
        public ActionResult Kitaplarım()
        {
            var kullanici = (string)Session["Mail"];
            var id = db.TBLUYELER.Where(x => x.MAİL == kullanici.ToString()).Select(z => z.ID).FirstOrDefault();
            var degerler = db.TBLHAREKET.Where(x => x.UYE == id).ToList(); 
            return View(degerler);
        }
        public ActionResult Duyurular()
        {
            var duyurulistesi = db.TBLDUYURULAR.ToList();
            return View(duyurulistesi);
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("GirisYap", "Login");
        }
        
    }
}

KutuphaneYonetimSistemi/KutuphaneYonetimSistemi/Views/Panelim/Duyurular.cshtml
@using KutuphaneYonetimSistemi.Models.Entity;
@model List<TBLDUYURULAR>
@{
    ViewBag.Title = "Duyurular";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}

<h2>Duyurular</h2>
<table class="table table-bordered">
    <tr>
      
        <th>Kategori</th>
        <th>Tarih</th>
      
     
        <th>İçerik</th>
    </tr>
    @foreach (var dyr in Model)
    {
        <tr>
            <td>@dyr.KATEGORI</td>

            <td>@Convert.ToDateTime(dyr.TARİH).ToString("dd/MM/yyyy")</td>
            <td>@dyr.ICERIK</td>

        </tr>

    }

</table>

KutuphaneYonetimSistemi/KutuphaneYonetimSistemi/Views/Panelim/Index.cshtml
@model KutuphaneYonetimSistemi.Models.Entity.TBLUYELER
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}
@using (Html.BeginForm("Index2", "Panelim", FormMethod.Post))
{
    <h2>Kütüphane Üye Profil Bilgileri</h2>
    <table class="table table-hover" style="margin-top:30px">
        <tr>
            <td>
                <label style="font-weight:bolder">Mail Adresi:</label>
                @HttpContext.Current.User.Identity.Name
            </td>
        </tr>



        <tr>
            <td>

                @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>

                @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>

                @Html.TextBoxFor(x => x.KULLANICIADI, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>

                @Html.TextBoxFor(x => x.SİFRE, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>

                @Html.TextBoxFor(x => x.FOTOGRAF, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>

                @Html.TextBoxFor(x => x.OKUL, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                <button class="btn btn-warning"> Şifre Güncelle</button>
            </td>
        </tr>
    </table>
}

KutuphaneYonetimSistemi/KutuphaneYonetimSistemi/Views/Panelim/Kitaplarım.cshtml
@using KutuphaneYonetimSistemi.Models.Entity
@model List<TBLHAREKET>

@{
    ViewBag.Title = "Kitaplarım";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}
<br />
<h2>Kitap Geçmişim</h2>
<br />

<table class="table table-bordered">
    <tr>

        <th>Kitap Adı</th>

        <th>Alış Tarihi</th>
        <th> Üye İade Tarihi</th>

     

    </tr>
    @foreach (var k in Model)
        {
            <tr>
               
                <td>@k.TBLKİTAP.AD</td>
                <td>@k.TBLPERSONEL.PERSONEL</td>
                <td>@Convert.ToDateTime(k.ALISTARİH).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(k.UYEGETİRTARİH).ToString("dd/MM/yyyy")</td>

                

            </tr>
        }
</table>